### ISSUE TITLE
Type error on CSM patrol list

### ISSUE THREAD

**Issue by smelc** [tbagrel1/datasheet_aggregator_10th#5]
As of 367fa4dcb4b3f93b1a5c73ff9c7868a70532dd3c, I'm observing the following failure:

```shell
→ ./src/__main__.py -i prince_patrol.txt 
Parsed army header of 'Prince Patrol' (Chaos Space Marines) with 625/1000 points!
Loading 'data/pdf_index/Chaos Space Marines.yaml'...
Traceback (most recent call last):
  File "/home/churlin/tools/datasheet_aggregator_10th/./src/__main__.py", line 376, in main
    convert_list_to_pdf(
  File "/home/churlin/tools/datasheet_aggregator_10th/./src/__main__.py", line 518, in convert_list_to_pdf
    load_rec_index(main_army_index_path, army_rules, detachments, armoury_full_pages, armoury_half_pages, datasheet_dict, status_function)
  File "/home/churlin/tools/datasheet_aggregator_10th/./src/__main__.py", line 270, in load_rec_index
    for page_nb in content["armoury_half_pages"]:
TypeError: 'int' object is not iterable
```

on the following `prince_patrol.txt` list:

```
Prince Patrol (625 points)
Chaos Space Marines
Incursion (1000 points)
Slaves to Darkness


CHARACTER

Heretic Astartes Daemon Prince with Wings (215 points)
  • Mark of Chaos: Khorne
  • Warlord
  • 1x Hellforged weapons
    1x Infernal cannon
  • Enhancement: Talisman of Burning Blood


BATTLELINE

Cultist Mob (55 points)
  • Mark of Chaos: Khorne
  • 1x Cultist Champion
    • 1x Autopistol
      1x Brutal assault weapon
  • 9x Chaos Cultist
    • 9x Autopistol
      9x Brutal assault weapon


DEDICATED TRANSPORT

Chaos Rhino (75 points)
  • Mark of Chaos: Nurgle
  • 1x Armoured tracks
    1x Combi-bolter


OTHER DATASHEETS

Chosen (110 points)
  • Mark of Chaos: Slaanesh
  • 1x Chosen Champion
    • 1x Accursed weapon
      1x Bolt pistol
      1x Boltgun
  • 4x Chosen
    • 3x Accursed weapon
      2x Bolt pistol
      4x Boltgun
      1x Chaos Icon
      2x Plasma pistol
      1x Power fist
Obliterators (170 points)
  • Mark of Chaos: Tzeentch
  • 2x Obliterator
    • 2x Crushing fists
      2x Fleshmetal guns


```

**Comment by tbagrel1** [comment]
Indeed. It should be an easy fix. For the moment you can change the type of the field `armoury_half_pages` in `data/pdf_index/Chaos Space Marines.yaml` to a list and it should help.

**Comment by smelc** [comment]
> Indeed. It should be an easy fix. For the moment you can change the type of the field armoury_half_pages in data/pdf_index/Chaos Space Marines.yaml to a list and it should help.

:+1: I did that in https://github.com/tbagrel1/datasheet_aggregator_10th/pull/8

However, on the tip of 8, the infamous error is back :disappointed: 

```
./src/__main__.py -i prince_patrol.txt 
Parsed army header of 'Prince Patrol' (Chaos Space Marines) with 625/1000 points!
Loading 'data/pdf_index/Chaos Space Marines.yaml'...
Playing with army rule 'Chaos Space Marines' and detachment_rule 'Slaves to Darkness'!
Adding a first page with the list recap...
Traceback (most recent call last):
  File "/home/churlin/tools/datasheet_aggregator_10th/./src/__main__.py", line 376, in main
    convert_list_to_pdf(
  File "/home/churlin/tools/datasheet_aggregator_10th/./src/__main__.py", line 559, in convert_list_to_pdf
    add_annot(output_pdf.get_page(current_pages-1),rest_of_the_list, pos_params, annot_params, "\n\n", "")
  File "/home/churlin/tools/datasheet_aggregator_10th/./src/__main__.py", line 203, in add_annot
    l1, l2 = arrange_in_two(text_content, nb_lines_in_one_column, sep_p1, sep_p2)
  File "/home/churlin/tools/datasheet_aggregator_10th/./src/__main__.py", line 170, in arrange_in_two
    g[0] = sep_p1[1:] + g[0]
IndexError: list index out of range
```

@tbagrel1> did you push the fix for this one?
